name: Docker

on:
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Sha for image #HERE I SET A SHORT SHA USING GLOBAL GIT SHA(GITHUB_SHA), PRASING IT TO GET FIRST 7 CHARS (::7) AND SAVING IT TO GIT ENVS (>> $GITHUB_ENV)
        run: echo "s_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
       
      - name: metadata creator
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{secrets.DOCKERHUB_USERNAME}}/devops-python-test:
          tags: |
              type=raw,value=${{ env.SHORT_SHA }}

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Python docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
